version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: etl_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-fakestore_db}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl_app:
    build: .
    container_name: etl_pipeline
    depends_on:
      - postgres_db
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-fakestore_db}

volumes:
  pgdata: